### ISSUE TITLE
Feature Request: FreshRSS API support

### ISSUE THREAD

**Issue by playforvoices1** [poetaster/tidings#103]
Would nice to have a build in FreshRSS API support for feed managing.

**Comment by playforvoices1** [comment]
Finally, I want to read all of my 120 feeds inside Tidings. I use a hosted FreshRSS aggregator for browser based reading. Currently, OPML import isn't possible with Tidings, so I ask for an API access to an aggregator.

**Comment by poetaster** [comment]
Ok, I read the docs and the Google Reader apis are the ones with more support. Ok, so opml import....

**Comment by playforvoices1** [comment]
Yeah, OPML would be very nice at all.

**Comment by poetaster** [comment]
https://github.com/poetaster/tidings/releases/tag/1.4.1
