### ISSUE TITLE
Going to next post very buggy since version 0.5

### ISSUE THREAD

**Issue by ghost** [poetaster/tidings#19]
When I am reading a long post and then use the pulley menu to go to the next post, it does not start at the top of that post. Sometimes it even goes _below_ the whole post, so that I have to tap the screen to make it appear. Going to the previous post seems to work fine.

It worked fine in version 0.4.

I used http://yle.fi/uutiset/rss/paauutiset.rss to test it.
This is an example of how it looks when I go to the next post:
![Image of TidingsBug](https://cdn.mediacru.sh/0BG05XScJCaV.jpg)

**Comment by poetaster** [comment]
Seems to be fixed by the passage of time.
