### ISSUE TITLE
Preformatted text is cut off

### ISSUE THREAD

**Issue by inta** [poetaster/tidings#23]
Like the headline says, preformatted text like in code block is cut off horizontally.
I think that is caused by the HTML pre element as you can see it in this feed: http://lhorie.github.io/mithril-blog/feed.xml

I do not know what a proper solution would look like. Horizontal scrolling would be great, but that might conflict with left/right gestures. Allowing word wrap for pre elements would be an alternative and I think still better than cutting content off.

By the way - great app - I love it :)

**Comment by poetaster** [comment]
Yes, this is the pre tag. The simple viewers solution is to rotate. I can't really strip and re-format pre, since we have two types of view (slider and old pull up). In the one, the gesture won't work. If I make a new Scaling Richt Text thing for the slideshow view, I'll re-visit this.
