### ISSUE TITLE
Feature request: import OPML file

### ISSUE THREAD

**Issue by ilpianista** [poetaster/tidings#27]
Hi there, I follow almost 80 feeds and adding all them manually is a no-go. Is there a way to automatize addition? Maybe you could implement import from OPML file?
Thanks

**Comment by Knarf64** [comment]
I would love to see this feature too, I cloned the project, let's see what I can propose as pull request.

**Comment by playforvoices1** [comment]
One vote more for OPML file import / export function.

**Comment by pherjung** [comment]
As [asked](https://forum.sailfishos.org/t/tidings-rss-reader-issues/13672/40). GitHub doesn't allow to upload such files. So I ziped it…
[test.zip](https://github.com/poetaster/tidings/files/10805288/test.zip)

**Comment by poetaster** [comment]
> As [asked](https://forum.sailfishos.org/t/tidings-rss-reader-issues/13672/40). GitHub doesn't allow to upload such files. So I ziped it… [test.zip](https://github.com/poetaster/tidings/files/10805288/test.zip)

Thanks!

**Comment by playforvoices1** [comment]
Here 2 version of OPML files filled with a load of different feeds. 

[feeds_opml.zip](https://github.com/poetaster/tidings/files/10812284/feeds_opml.zip)

**Comment by poetaster** [comment]
https://github.com/poetaster/tidings/releases/tag/1.4.1
