### ISSUE TITLE
Take over maintenance.

### ISSUE THREAD

**Issue by poetaster** [poetaster/tidings#59]
Hi! I'm still fresh to QML development but would be willing to take responsibility for tidings if no one else does.

**Comment by pycage** [comment]
Hi! Thanks for your offer to take over maintenance. A lot of people will surely appreciate this, and I'm also happy about having found a new maintainer for Tidings. Thanks a lot!

**Comment by poetaster** [comment]
Thank you for the years of support! I've been using it since getting a Jollaphone in 2016.

**Comment by poetaster** [comment]
Ok, I'm it :)
