### ISSUE TITLE
Make aarch64 package available

### ISSUE THREAD

**Issue by llewelld** [poetaster/tidings#65]
It would be great to have an aarch64 version of the app available for Xperia 10II devices.

Using sfdk I found it built without alterations and seems to work nicely. Feel free to use this rpm if it helps (or I can build for a different version bump if there's one that would be better).

https://www.flypig.co.uk/dnload/dnload/sailfishos/harbour-tidings-0.8.2+master.20210510150547.8d576a3-1.aarch64.rpm

**Comment by poetaster** [comment]
It's up here and I'm posting to Jolla, now.
