### ISSUE TITLE
Filter by feed no longer working

### ISSUE THREAD

**Issue by gabrielgg** [poetaster/tidings#86]
On Feeds view (where you see the total items of each feed), when tapping on a particular feed, you don't get the items that belong to that feed.
Interestingly, you get the full list, but somehow ordered differently.
Can anyone else reproduce this? I'm pretty sure it used to work but admit that it isn't a feature that I used all the time. Indeed, I only ever used it for testing :)
I'll try to debug/see git history, but dropping this here for sanity check and in case somebody else fixes it faster than me.

**Comment by poetaster** [comment]
I think this is a won't fix since everything does seem to work as initially intended.
